/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class project2 extends javax.swing.JFrame {

    private boolean CBPREMIU;

    /**
     * Creates new form project2
     */
    public project2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBPREMIUM = new javax.swing.JCheckBox();
        CBSOLAR = new javax.swing.JCheckBox();
        CBPETRALIT = new javax.swing.JCheckBox();
        CBPERTAMAX = new javax.swing.JCheckBox();
        TFPREMIUM = new javax.swing.JTextField();
        TFSOLAR = new javax.swing.JTextField();
        TFPETRALIT = new javax.swing.JTextField();
        TFPERTAMAX = new javax.swing.JTextField();
        BTBAYAR = new javax.swing.JButton();
        LBTOTAL = new javax.swing.JLabel();
        TFTOTAL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PERTAMINA MINI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("BAHAN BAKAR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("LITER");

        buttonGroup1.add(CBPREMIUM);
        CBPREMIUM.setText("PREMIUM  Rp.7000/L");
        CBPREMIUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPREMIUMActionPerformed(evt);
            }
        });

        buttonGroup1.add(CBSOLAR);
        CBSOLAR.setText("SOLAR  Rp.9600/L");
        CBSOLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSOLARActionPerformed(evt);
            }
        });

        buttonGroup1.add(CBPETRALIT);
        CBPETRALIT.setText("PETRALIT  Rp.7700/L");
        CBPETRALIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPETRALITActionPerformed(evt);
            }
        });

        buttonGroup1.add(CBPERTAMAX);
        CBPERTAMAX.setText("PERTAMAX  Rp.9900/L");
        CBPERTAMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPERTAMAXActionPerformed(evt);
            }
        });

        TFPREMIUM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFPREMIUM.setText("0");
        TFPREMIUM.setToolTipText("");
        TFPREMIUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPREMIUMActionPerformed(evt);
            }
        });

        TFSOLAR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFSOLAR.setText("0");
        TFSOLAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSOLARActionPerformed(evt);
            }
        });

        TFPETRALIT.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFPETRALIT.setText("0");
        TFPETRALIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPETRALITActionPerformed(evt);
            }
        });

        TFPERTAMAX.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFPERTAMAX.setText("0");
        TFPERTAMAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPERTAMAXActionPerformed(evt);
            }
        });

        BTBAYAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTBAYAR.setText("BAYAR");
        BTBAYAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBAYARActionPerformed(evt);
            }
        });

        LBTOTAL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBTOTAL.setText("TOTAL ");

        TFTOTAL.setEditable(false);
        TFTOTAL.setText("Rp.0");
        TFTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTOTALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(LBTOTAL)
                        .addGap(18, 18, 18)
                        .addComponent(TFTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BTBAYAR))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CBPERTAMAX)
                                        .addComponent(CBSOLAR, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CBPETRALIT, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(CBPREMIUM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFPREMIUM, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(TFPERTAMAX)
                                    .addComponent(TFPETRALIT)
                                    .addComponent(TFSOLAR))))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPREMIUM)
                    .addComponent(TFPREMIUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBSOLAR)
                    .addComponent(TFSOLAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPETRALIT)
                    .addComponent(TFPETRALIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBPERTAMAX)
                    .addComponent(TFPERTAMAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBTOTAL)
                    .addComponent(TFTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTBAYAR)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBPETRALITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPETRALITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPETRALITActionPerformed

    private void CBPREMIUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPREMIUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPREMIUMActionPerformed

    private void TFPREMIUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPREMIUMActionPerformed
        // TODO add your handling code here:
            double premium=Double.parseDouble(TFPREMIUM.getText())*7000;
            TFTOTAL.setText("Rp."+premium+"0");
    }//GEN-LAST:event_TFPREMIUMActionPerformed

    private void TFSOLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSOLARActionPerformed
        // TODO add your handling code here:
         double solar=Double.parseDouble(TFSOLAR.getText())*9600;
        TFTOTAL.setText("Rp."+solar+"0");
    }//GEN-LAST:event_TFSOLARActionPerformed

    private void TFPETRALITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPETRALITActionPerformed
        // TODO add your handling code here:
         double petralit=Double.parseDouble(TFPETRALIT.getText())*7700;
        TFTOTAL.setText("Rp."+petralit+"0");
    }//GEN-LAST:event_TFPETRALITActionPerformed

    private void TFPERTAMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPERTAMAXActionPerformed
        // TODO add your handling code here:
         double pertamax=Double.parseDouble(TFPERTAMAX.getText())*9900;
        TFTOTAL.setText("Rp."+pertamax+"0");
    }//GEN-LAST:event_TFPERTAMAXActionPerformed

    private void CBSOLARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSOLARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSOLARActionPerformed

    private void BTBAYARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBAYARActionPerformed
        // TODO add your handling code here:
        bayar b= new bayar();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTBAYARActionPerformed

    private void CBPERTAMAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPERTAMAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPERTAMAXActionPerformed

    private void TFTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTOTALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBAYAR;
    private javax.swing.JCheckBox CBPERTAMAX;
    private javax.swing.JCheckBox CBPETRALIT;
    private javax.swing.JCheckBox CBPREMIUM;
    private javax.swing.JCheckBox CBSOLAR;
    private javax.swing.JLabel LBTOTAL;
    private javax.swing.JTextField TFPERTAMAX;
    private javax.swing.JTextField TFPETRALIT;
    private javax.swing.JTextField TFPREMIUM;
    private javax.swing.JTextField TFSOLAR;
    private javax.swing.JTextField TFTOTAL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void CBPREMIUM(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
